application: cybersharesnet
version: prod
runtime: python27
api_version: 1
threadsafe: true


builtins:
- appstats: on
- deferred: on
- remote_api: on

handlers:

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /css
  static_dir: css
- url: /js
  static_dir: js
- url: /images
  static_dir: images

- url: .*
  script: main.application

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
- name: lxml
  version: latest
- name: pycrypto
  version: latest

pagespeed:
  enabled_rewriters:
  - ImageAddDimensions
  - MinifyCss
  - InlineJs
  - InlineImages
  - CollapseWhitespace
  - CombineHeads
  - ElideAttributes
  - RemoveComments
  - RemoveQuotes
  - LeftTrimUrls
  - DeferJs

skip_files: |
 ^(.*/)?(
 (app\.yaml)|
 (#.*#)|
 (.*~)|
 (.*\.py[co])|
 (.*/RCS/.*)|
 (\..*)|
 (.*/\.svn/.*)|
 (.*/Thumbs\.db)|
 README.md|
 run_deploy_contracts.sh|
 )$
